# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: run.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trun.proto\x12\x06runner\"5\n\x08LoadInfo\x12\x17\n\x0f\x66ree_containers\x18\x01 \x01(\x04\x12\x10\n\x08\x63pu_load\x18\x02 \x01(\x04\"@\n\rCodeWithTests\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0cprogram_code\x18\x02 \x01(\x0c\x12\r\n\x05tests\x18\x03 \x03(\t\"O\n\x0c\x43heckResults\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x03(\t\x12#\n\tload_info\x18\x03 \x01(\x0b\x32\x10.runner.LoadInfo2G\n\x06Runner\x12=\n\x0c\x43heckProgram\x12\x15.runner.CodeWithTests\x1a\x14.runner.CheckResults\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'run_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOADINFO']._serialized_start=21
  _globals['_LOADINFO']._serialized_end=74
  _globals['_CODEWITHTESTS']._serialized_start=76
  _globals['_CODEWITHTESTS']._serialized_end=140
  _globals['_CHECKRESULTS']._serialized_start=142
  _globals['_CHECKRESULTS']._serialized_end=221
  _globals['_RUNNER']._serialized_start=223
  _globals['_RUNNER']._serialized_end=294
# @@protoc_insertion_point(module_scope)
